spring.application.name=GestaoFuncionarios
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

//.env
app.jornada.padrao-minutos=${JORNADA_PADRAO_MINUTOS}
app.jornada.desconto-variavel=${DESCONTO_MINUTOS_DIARIOS_VARIAVEL}
app.financeiro.diaria-padrao=${DIARIA_PADRAO}
app.financeiro.valor-hora-extra=${VALOR_HORA_EXTRA}